name: Veracode lf-ui-components-services-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: 'create an empty ./veracode folder'
        run: 'mkdir -p ./veracode'
        
      - name: 'Compress UI Components'
        run: tar -czvf ./veracode/ui-components-services.tar.gz ./src

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./veracode

      - name: echo github run attempt
        run: echo ${{ github.run_attempt }} ${{  github.event.pull_request.head.repo.owner.login }}
