name: Veracode lf-ui-components-services-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  veracode_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: 'create an empty ./veracode folder'
        run: 'mkdir -p ./veracode'
        
      - name: 'Compress UI Components'
        run: tar -czvf ./veracode/ui-components-services.tar.gz ./src

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ui-components-services
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./veracode

      - name: echo github run attempt
        run: echo ${{ github.run_attempt }} ${{  github.event.pull_request.head.repo.owner.login }}

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'SharePoint Integration'
          createprofile: true
          filepath: 'veracode'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          teams: 'Application Component - Shared'

      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.6
        with:
          create-issues: false
          allow-dirty: true
          recursive: true